version: '3.8'

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - GITEA_ADMIN_USER=admin
      - GITEA_ADMIN_PASSWORD=admin123
    volumes:
      - ./gitea/app.ini:/data/gitea/conf/app.ini
      - ./gitea/init:/docker-entrypoint-init.d
      - gitea_data:/data
    ports:
      - "3000:3000"
    networks:
      - devops-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 5

  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ./jenkins/casc:/var/jenkins_home/casc_configs
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
    ports:
      - "8080:8080"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      CASC_JENKINS_CONFIG: "/var/jenkins_home/casc_configs"
    networks:
      - devops-net
    depends_on:
      gitea:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 4.4.4.4
networks:
  devops-net:
    driver: bridge

volumes:
  gitea_data:
  jenkins_data:
